import { StyleSheet } from 'react-native';

export const dailyFlowStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f8f6',
  },
  // Date Scroll Container (replaces header)
  dateScrollContainer: {
    paddingVertical: 12,
    paddingTop: 8,
    backgroundColor: '#f6f8f6CC',
    borderBottomWidth: 0,
  },
  // Horizontal Date Scroll
  horizontalDateScroll: {
    flexGrow: 0,
  },
  horizontalDateContent: {
    paddingHorizontal: 16,
    gap: 10,
  },
  dateCard: {
    width: 64,
    height: 80,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: '#2bee6c',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0,
    shadowRadius: 8,
    elevation: 0,
  },
  dateCardToday: {
    shadowOpacity: 0.3,
    elevation: 4,
  },
  dateCardSelected: {
    shadowOpacity: 0.2,
    elevation: 3,
  },
  dateCardDay: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 4,
  },
  dateCardDate: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  // Modern Activity List
  modernActivityListWrapper: {
    flex: 1,
  },
  modernActivityList: {
    flex: 1,
  },
  modernActivityListContent: {
    padding: 16,
    paddingBottom: 100,
  },
  modernActivitiesWrapper: {
    gap: 12,
  },
  modernActivityCardWrapper: {
    marginBottom: 12,
    position: 'relative',
    overflow: 'visible',
  },
  modernDeleteContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 60,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  modernDeleteTouchable: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 24,
  },
  modernActivityCard: {
    borderRadius: 12,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#2bee6c80',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: 'hidden',
    position: 'relative',
    zIndex: 2,
  },
  modernChevronIndicator: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  modernChevronIndicatorFixed: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  modernChevronButton: {
    paddingRight: 8,
    paddingVertical: 16,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  chevronContainer: {
    width: 20,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  chevronLine: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderLeftWidth: 3,
    borderRadius: 2,
  },
  chevronTop: {
    top: 4,
    borderTopWidth: 3,
    transform: [{ rotate: '-45deg' }],
  },
  chevronBottom: {
    bottom: 4,
    borderBottomWidth: 3,
    transform: [{ rotate: '45deg' }],
  },
  modernActivityContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 16,
  },
  modernActivityIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#2bee6c30',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernActivityEmoji: {
    fontSize: 24,
  },
  modernActivityInfo: {
    flex: 1,
  },
  modernActivityTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  modernActivityDetail: {
    fontSize: 13,
    fontWeight: 'normal',
    marginTop: 2,
  },
  modernRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 6,
  },
  modernRatingIcon: {
    fontSize: 20,
  },
  modernRatingText: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  modernRatingBadgeSmall: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 3,
  },
  modernRatingIconSmall: {
    fontSize: 14,
  },
  modernRatingTextSmall: {
    fontSize: 12,
    fontWeight: 'bold',
  },
  modernDeleteButton: {
    position: 'absolute',
    right: 16,
    top: 16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0,
  },
  // FAB Styles
  fabContainer: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    alignItems: 'flex-end',
    gap: 16,
  },
  quickActivitiesCard: {
    width: 256,
    borderRadius: 16,
    padding: 16,
    backgroundColor: '#283944',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  quickActivitiesTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
  },
  quickActivityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  quickActivityIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickActivityEmoji: {
    fontSize: 24,
  },
  quickActivityInfo: {
    flex: 1,
  },
  quickActivityTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  quickActivitySubtitle: {
    fontSize: 12,
    color: '#9ca3af',
  },
  fabButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  fabButtonSmall: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabButtonLarge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  fabIcon: {
    fontSize: 28,
    color: '#fff',
  },
  fabIconLarge: {
    fontSize: 36,
    color: '#fff',
  },
  dateHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  navButton: {
    padding: 12,
    borderRadius: 25,
    backgroundColor: '#6366f1',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  navButtonText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  dateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    textAlign: 'center',
    flex: 1,
  },
  activitiesContainer: {
    flex: 1,
    padding: 16,
  },
  scrollContentContainer: {
    paddingBottom: 200,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 100,
  },
  emptyText: {
    fontSize: 18,
    color: '#666',
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999',
  },
  activityCard: {
    backgroundColor: '#fff',
    padding: 18,
    marginBottom: 12,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  activityCardPressed: {
    transform: [{ scale: 0.98 }],
    opacity: 0.8,
  },
  activityCardContainer: {
    position: 'relative',
    marginBottom: 12,
    overflow: 'visible',
  },
  activityCardInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  swipeToggleButtonWrapper: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 50,
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  swipeToggleButton: {
    paddingRight: 0,
    paddingVertical: 8,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  swipeIndicatorContainer: {
    width: 20,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  chevronLine: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderLeftWidth: 3,
    borderRadius: 2,
  },
  chevronTop: {
    top: 4,
    borderTopWidth: 3,
    transform: [{ rotate: '-45deg' }],
  },
  chevronBottom: {
    bottom: 4,
    borderBottomWidth: 3,
    transform: [{ rotate: '45deg' }],
  },
  activityCardDeleting: {
    opacity: 0,
    transform: [{ scale: 0.7 }],
  },
  activityCardCompleted: {
    backgroundColor: '#f0fdf4',
    borderColor: '#22c55e',
    borderWidth: 2,
    shadowColor: '#22c55e',
    shadowOpacity: 0.15,
  },
  activityCardSwiped: {
    transform: [{ translateX: -80 }],
  },
  deleteButtonContainer: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 12,
    width: 70,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    borderTopRightRadius: 16,
    borderBottomRightRadius: 16,
    zIndex: 1,
  },
  deleteButton: {
    padding: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activityCardPressable: {
    flex: 1,
  },
  activityContent: {
    flex: 1,
  },
  activityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  categoryEmoji: {
    fontSize: 22,
    marginRight: 10,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    flex: 1,
  },
  activityDetail: {
    fontSize: 13,
    color: '#888',
    fontStyle: 'italic',
    marginBottom: 2,
  },
  activityTime: {
    fontSize: 12,
    color: '#666',
  },
  addButtonsContainer: {
    position: 'absolute',
    bottom: 50,
    right: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  quickAddButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#f59e0b',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    shadowColor: '#f59e0b',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    borderWidth: 2,
    borderColor: '#fff',
  },
  quickAddButtonText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: 'bold',
  },
  addButton: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#6366f1',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
    borderWidth: 2,
    borderColor: '#fff',
  },
  addButtonText: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
  },
  quickAddOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'transparent', // Will be overridden by colors.modalBackground
    zIndex: 1000,
  },
  quickAddMenu: {
    position: 'absolute',
    bottom: 100,
    right: 30,
    backgroundColor: '#fff', // Will be overridden by colors.modalContent
    borderRadius: 15,
    padding: 15,
    minWidth: 200,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  quickAddTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333', // Will be overridden by colors.text
    marginBottom: 10,
    textAlign: 'center',
  },
  quickAddItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginBottom: 5,
    backgroundColor: '#f8f9fa', // Will be overridden by colors.surfaceSecondary
  },
  quickAddEmoji: {
    fontSize: 20,
    marginRight: 12,
  },
  quickAddText: {
    fontSize: 14,
    color: '#333', // Will be overridden by colors.text
    flex: 1,
  },
  quickAddTextContainer: {
    flex: 1,
  },
  quickAddDetail: {
    fontSize: 12,
    color: '#666', // Will be overridden by colors.textSecondary
    fontStyle: 'italic',
    marginTop: 2,
  },
  statsContainer: {
    paddingHorizontal: 20,
    paddingVertical: 5,
  },
  streakCard: {
    borderRadius: 8,
    padding: 8,
    marginBottom: 5,
    borderWidth: 1,
    borderStyle: 'solid',
  },
  streakText: {
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  goalCard: {
    borderRadius: 8,
    padding: 10,
    marginBottom: 5,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: '#e2e8f0',
  },
  goalProgressItem: {
    marginBottom: 8,
  },
  goalProgressLabel: {
    fontSize: 12,
    fontWeight: '500',
    marginBottom: 6,
  },
  progressBarContainer: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
  },
  compactStatsCard: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 5,
  },
  compactStatsText: {
    fontSize: 15,
    color: '#64748b',
    textAlign: 'center',
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    elevation: 1000,
  },
  keyboardAvoidingView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: '90%',
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 24,
    color: '#1e293b',
  },
  inputLabel: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
    color: '#1e293b',
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    padding: 12,
    fontSize: 16,
    marginBottom: 15,
    backgroundColor: '#f9f9f9',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  categoryButton: {
    width: '30%',
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  selectedCategory: {
    borderColor: '#6366f1',
    backgroundColor: '#eef2ff',
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  categoryName: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
  },
  helpText: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
    marginTop: -10,
    marginBottom: 15,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#666',
  },
  saveButton: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#6366f1',
    alignItems: 'center',
    marginLeft: 12,
    shadowColor: '#6366f1',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  addButtonPressed: {
    transform: [{ scale: 0.95 }],
    opacity: 0.8,
  },
  dateButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  datePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  datePickerPanel: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 20,
    width: '90%',
    maxHeight: '75%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 20,
    position: 'relative',
  },
  datePickerCloseX: {
    position: 'absolute',
    top: 16,
    right: 16,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#f3f4f6',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  datePickerCloseXText: {
    fontSize: 24,
    color: '#6b7280',
    fontWeight: 'bold',
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 8,
    gap: 12,
  },
  calendarHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2bee6c20',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#2bee6c50',
  },
  calendarHeaderText: {
    fontSize: 17,
    fontWeight: 'bold',
    color: '#1e293b',
    marginRight: 4,
  },
  calendarHeaderArrow: {
    fontSize: 12,
    color: '#2bee6c',
    fontWeight: 'bold',
  },
  goToTodayButtonInline: {
    backgroundColor: '#2bee6c',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 40,
  },
  goToTodayTextInline: {
    fontSize: 16,
    color: '#000',
    fontWeight: 'bold',
  },
  calendarWeekHeader: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  calendarWeekDayText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    color: '#2bee6c',
    paddingVertical: 8,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  calendarDay: {
    width: '14.28%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 0,
    marginVertical: 2,
  },
  calendarDayOtherMonth: {
    opacity: 0.3,
  },
  calendarDayToday: {
    backgroundColor: '#2bee6c30',
    borderWidth: 2,
    borderColor: '#2bee6c',
  },
  calendarDaySelected: {
    backgroundColor: '#2bee6c',
    borderWidth: 0,
  },
  calendarDayText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  calendarDayTextOtherMonth: {
    color: '#9ca3af',
  },
  calendarDayTextToday: {
    color: '#1e293b',
    fontWeight: 'bold',
  },
  calendarDayTextSelected: {
    color: '#000',
    fontWeight: 'bold',
  },
  datePickerCloseButton: {
    backgroundColor: '#6b7280',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    flex: 1,
    marginLeft: 6,
  },
  datePickerCloseText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  goToTodayButton: {
    backgroundColor: '#2bee6c',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginTop: 8,
    width: '100%',
    shadowColor: '#2bee6c',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  goToTodayText: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
  },
  pickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerPanel: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 24,
    width: '85%',
    maxHeight: '65%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 20,
  },
  pickerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: 20,
    textAlign: 'center',
  },
  pickerScrollView: {
    maxHeight: 300,
  },
  pickerOption: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 8,
    backgroundColor: 'transparent',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  pickerOptionSelected: {
    backgroundColor: '#2bee6c',
    borderColor: '#2bee6c',
    shadowColor: '#2bee6c',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  pickerOptionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  pickerOptionTextSelected: {
    color: '#000',
    fontWeight: 'bold',
  },
  completionSection: {
    marginTop: 20,
    marginBottom: 16,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#6366f1',
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    backgroundColor: '#6366f1',
  },
  checkboxText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  checkboxLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#374151',
  },
  ratingSection: {
    marginTop: 16,
    marginBottom: 16,
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  starButton: {
    padding: 2,
    marginRight: 1,
  },
  star: {
    fontSize: 20,
    color: '#d1d5db',
  },
  starFilled: {
    color: '#fbbf24',
  },
  ratingText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6b7280',
    marginTop: 8,
    textAlign: 'center',
  },
  activityTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  completionBadge: {
    backgroundColor: '#10b981',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  completionText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  activityRating: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  ratingLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6b7280',
    marginRight: 8,
  },
  ratingBadge: {
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  ratingBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#fff',
  },
  ratingBadgeCompleted: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  ratingBadgeTextCompleted: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  activityStars: {
    flexDirection: 'row',
  },
  activityStar: {
    fontSize: 12,
    color: '#d1d5db',
    marginRight: 1,
  },
  activityStarFilled: {
    color: '#fbbf24',
  },
  seriesInputContainer: {
    marginTop: 8,
  },
  seriesInputRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 12,
  },
  seriesInputHalf: {
    flex: 1,
    marginHorizontal: 4,
  },
  seriesInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 4,
  },
  seriesInput: {
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
    fontSize: 16,
    textAlign: 'center',
  },
  addRowButton: {
    backgroundColor: '#6366f1',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginTop: 12,
    alignItems: 'center',
  },
  addRowButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  removeRowButton: {
    backgroundColor: '#ef4444',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  removeRowButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  categoryGroup: {
    marginBottom: 20,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    marginTop: 4,
  },
  categoryContent: {
    flex: 1,
  },
  categoryLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  categoryHorizontalLine: {
    height: 1,
    backgroundColor: '#e5e7eb',
    width: '100%',
  },
  categoryTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  categoryCount: {
    fontSize: 11,
    fontWeight: '500',
    color: '#9ca3af',
    marginLeft: 4,
  },
  categoryArrow: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6366f1',
    marginLeft: 6,
    width: 16,
    textAlign: 'center',
  },
  completionIcon: {
    backgroundColor: '#047857',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completionIconText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  // Modern Modal Styles
  modernModalContainer: {
    flex: 1,
    backgroundColor: '#102216',
  },
  modernModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    paddingBottom: 8,
    backgroundColor: '#102216',
  },
  modernModalClose: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  modernModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    flex: 1,
  },
  modernModalSave: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  modernModalSaveText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2bee6c',
  },
  modernModalScroll: {
    flex: 1,
  },
  modernModalContent: {
    padding: 16,
    paddingBottom: 100,
  },
  modernCategorySection: {
    marginBottom: 20,
  },
  modernCategorySectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 10,
  },
  modernCategoryScroll: {
    gap: 8,
    paddingVertical: 4,
  },
  modernCategoryPill: {
    height: 40,
    paddingHorizontal: 20,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernCategoryPillText: {
    fontSize: 14,
  },
  modernSectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 12,
    marginTop: 8,
  },
  modernFormFields: {
    gap: 20,
  },
  modernInputGroup: {
    gap: 8,
  },
  modernInputLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffffE6',
  },
  modernTextInput: {
    height: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#2bee6c50',
    backgroundColor: '#2bee6c1A',
    paddingHorizontal: 15,
    fontSize: 16,
    color: '#fff',
  },
  modernSeriesContainer: {
    gap: 12,
  },
  modernSeriesRow: {
    flexDirection: 'row',
    gap: 16,
    alignItems: 'flex-end',
  },
  modernSeriesInputHalf: {
    flex: 1,
    gap: 8,
  },
  modernRemoveButton: {
    width: 32,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernAddSeasonButton: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#2bee6c30',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  modernAddSeasonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2bee6c',
  },
  modernCheckboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modernCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#2bee6c80',
    backgroundColor: '#2bee6c1A',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernCheckboxChecked: {
    backgroundColor: '#2bee6c',
    borderColor: '#2bee6c',
  },
  modernCheckboxLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffffE6',
  },
  modernRatingSection: {
    gap: 12,
  },
  modernStarsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modernModalFooter: {
    padding: 16,
    paddingTop: 8,
    backgroundColor: '#102216',
  },
  modernSaveButton: {
    height: 56,
    borderRadius: 12,
    backgroundColor: '#2bee6c',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modernSaveButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#102216',
  },
});


