import { StyleSheet } from 'react-native';

export const reportsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    backgroundColor: '#fff',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  viewModeSelector: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  viewModeButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  viewModeButtonActive: {
    backgroundColor: '#007AFF',
  },
  viewModeText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#64748b',
  },
  viewModeTextActive: {
    color: '#fff',
  },
  dateNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButton: {
    padding: 8,
  },
  dateButton: {
    flex: 1,
    alignItems: 'center',
  },
  dateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  tab: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#007AFF',
  },
  tabText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#64748b',
  },
  activeTabText: {
    color: '#007AFF',
  },
  content: {
    flex: 1,
  },
  categoryCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginVertical: 8,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  categoryEmoji: {
    fontSize: 18,
    marginRight: 10,
  },
  categoryName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1e293b',
    flex: 1,
  },
  categoryDetails: {
    marginTop: 6,
  },
  categoryDetailRow: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#f8fafc',
    borderRadius: 6,
    marginBottom: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#6366f1',
  },
  categoryDetailRowCompleted: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: '#f0fdf4',
    borderRadius: 6,
    marginBottom: 4,
    borderLeftWidth: 3,
    borderLeftColor: '#10b981',
    borderRightWidth: 3,
    borderRightColor: '#10b981',
    borderTopWidth: 1,
    borderTopColor: '#10b981',
    borderBottomWidth: 1,
    borderBottomColor: '#10b981',
  },
  categoryDetailText: {
    fontSize: 13,
    color: '#374151',
    fontWeight: '500',
    lineHeight: 18,
    flex: 1,
  },
  dayCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginVertical: 8,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  dayHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  activityCountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  activityCountText: {
    fontSize: 14,
    color: '#666',
  },
  dailyProgressBar: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    marginLeft: 12,
    overflow: 'hidden',
  },
  dailyProgressFill: {
    height: '100%',
    borderRadius: 3,
  },
  dayCategoryIcons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 8,
    marginHorizontal: 16,
    gap: 4,
  },
  dayCategoryIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f5f9',
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginHorizontal: 1,
  },
  dayCategoryEmoji: {
    fontSize: 10,
    marginRight: 3,
  },
  dayCategoryCount: {
    fontSize: 10,
    fontWeight: '600',
    color: '#475569',
  },
  dayName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  dayDate: {
    fontSize: 14,
    color: '#64748b',
  },
  activityCount: {
    fontSize: 14,
    color: '#007AFF',
    fontWeight: '500',
  },
  expandedDayDetails: {
    backgroundColor: '#f8fafc',
    marginHorizontal: 20,
    marginBottom: 8,
    borderRadius: 8,
    padding: 12,
    borderLeftWidth: 3,
    borderLeftColor: '#6366f1',
  },
  dayActivityItem: {
    backgroundColor: '#fff',
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    position: 'relative',
  },
  dayActivityItemCompleted: {
    backgroundColor: '#f0fdf4',
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
    borderWidth: 2,
    borderColor: '#10b981',
    position: 'relative',
  },
  dayActivityContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  dayActivityEmoji: {
    fontSize: 14,
    marginRight: 6,
  },
  dayActivityTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1e293b',
    flex: 1,
  },
  goalProgressContainer: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 20,
  },
  goalProgressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  goalProgressTitle: {
    fontSize: 16,
    fontWeight: '600',
  },
  goalProgressItem: {
    marginBottom: 16,
  },
  goalProgressItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  goalProgressLabel: {
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  goalCompletedBadge: {
    fontSize: 12,
    fontWeight: '600',
    marginLeft: 8,
  },
  progressBarContainer: {
    height: 8,
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
  },
  dayActivityCompletedContainer: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#10b981',
    borderRadius: 12,
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayActivityCompleted: {
    fontSize: 12,
    color: '#fff',
    fontWeight: 'bold',
  },
  dayActivityDetail: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 2,
    fontStyle: 'italic',
    lineHeight: 16,
  },
  dayActivityRating: {
    fontSize: 11,
    color: '#f59e0b',
    fontWeight: '600',
  },
  weekCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginVertical: 8,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  weekHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  weekName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  weekDate: {
    fontSize: 14,
    color: '#007AFF',
    fontWeight: '500',
  },
  expandedWeekDetails: {
    marginTop: 12,
    gap: 8,
  },
  emptyStateCard: {
    backgroundColor: '#fff',
    marginHorizontal: 20,
    marginVertical: 20,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  emptyStateEmoji: {
    fontSize: 48,
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1e293b',
    textAlign: 'center',
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  emptyStateDescription: {
    fontSize: 14,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },
  emptyStateButton: {
    backgroundColor: '#007AFF',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  emptyStateButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  wrappedHeaderCard: {
    borderRadius: 20,
    padding: 32,
    marginBottom: 24,
    marginHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 120,
  },
  wrappedHeaderTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  wrappedCard: {
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    marginHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  wrappedCardEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  wrappedCardNumber: {
    fontSize: 48,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    textAlign: 'center',
  },
  wrappedCardLabel: {
    fontSize: 18,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 4,
  },
  wrappedCardSubtext: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.9,
    textAlign: 'center',
  },
  wrappedCardTopActivity: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.8,
    textAlign: 'center',
    marginTop: 12,
    fontStyle: 'italic',
  },
  wrappedChartContainer: {
    marginTop: 20,
    width: '100%',
    paddingHorizontal: 8,
  },
  wrappedCardNumberTouchable: {
    width: '100%',
    alignItems: 'center',
  },
  wrappedCardNumberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  wrappedCardChevron: {
    marginLeft: 8,
    opacity: 0.8,
  },
  wrappedCardDetails: {
    width: '100%',
    marginTop: 20,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.3)',
  },
  wrappedCardDetailItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  wrappedCardDetailItemLast: {
    borderBottomWidth: 0,
  },
  wrappedCardDetailTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
    flex: 1,
  },
  wrappedCardDetailValue: {
    fontSize: 13,
    fontWeight: '500',
    color: '#fff',
    opacity: 0.9,
    marginLeft: 12,
  },
});

